Improve CI

diff --git a/.github/workflows/reusable-CI-workflow.yml b/.github/workflows/reusable-CI-workflow.yml
--- a/.github/workflows/reusable-CI-workflow.yml
+++ b/.github/workflows/reusable-CI-workflow.yml
@@ -3,80 +3,126 @@ name: 'CI reusable workflow'
 on:
   workflow_call:
 
+permissions:
+  contents: read
+
 env:
+  COMPOSER_PREFER_STABLE: '1'
   TEST_OUTPUT_STYLE: pretty
-  COMPOSER_OPTIONS: --optimize-autoloader
 
 jobs:
-  tests:
-    name: PHP ${{ matrix.php-version }} - Symfony ${{ matrix.symfony-version }}
+  fetch-supported-versions:
+    name: Fetch supported versions
     runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    outputs:
+      php-min: ${{ steps.fetch-php-versions.outputs.min }}
+      php-max: ${{ steps.fetch-php-versions.outputs.max }}
+      php-next: ${{ steps.fetch-php-versions.outputs.next }}
+      symfony-min: ${{ steps.fetch-symfony-versions.outputs.min }}
+      symfony-max: ${{ steps.fetch-symfony-versions.outputs.max }}
+      symfony-next: ${{ steps.fetch-symfony-versions.outputs.next }}
+    steps:
+      - name: Fetch supported versions file
+        id: fetch-file
+        uses: yoanm/gha-supported-versions-parser/github-downloader@v1
+        with:
+          file-path: .github/workflows/supported-versions.json
+
+      - name: Fetch PHP supported versions
+        id: fetch-php-versions
+        uses: yoanm/gha-supported-versions-parser@v1
+        with:
+          path: ${{ steps.fetch-file.outputs.path }}
+          dependency: php
+
+      - name: Fetch Symfony supported versions
+        id: fetch-symfony-versions
+        uses: yoanm/gha-supported-versions-parser@v1
+        with:
+          path: ${{ steps.fetch-file.outputs.path }}
+          dependency: symfony
+
+  tests:
+    name: ${{ matrix.job-name }}
+    needs: [fetch-supported-versions]
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
     env:
       COVERAGE_TYPE: none
+      COVERAGE_OUTPUT_STYLE: clover
     strategy:
       fail-fast: true
-      max-parallel: 4
       matrix:
         include:
-          # Bare minimum => Lowest versions allowed by composer config
-          - symfony-version: '4.4'
-            php-version: '8.0'
-            composer-flag: --prefer-lowest
-          # Up to date versions => Latest versions allowed by composer config
-          - symfony-version: '5.4'
-            php-version: '8.2'
-          # Late symfony migration => Lowest symfony version with latest minor php version allowed by composer config
-          - symfony-version: '4.4'
-            php-version: '8.2'
-            composer-flag: --prefer-lowest
-          # Late php migration => Latest symfony version with lowest minor php version allowed by composer config
-          - symfony-version: '5.4'
-            php-version: '8.0'
-          # Symfony 6.0 latest
-          - symfony-version: '6.0'
-            php-version: '8.2'
-          # Symfony 6.0 lowest
-          - symfony-version: '6.0'
-            php-version: '8.0'
-            composer-flag: --prefer-lowest
+          - job-name: Up to date versions # => Highest versions allowed by composer config
+            php-version: '${{ needs.fetch-supported-versions.outputs.php-max }}'
+            symfony-version: '${{ needs.fetch-supported-versions.outputs.symfony-max }}'
+            # Fix - behat/gherkin => Avoid issue with behat <-> gherkin packages (See https://github.com/Behat/Gherkin/issues/317)
+            pkg-extra-constraints: behat/gherkin:~4.12.0
+          - job-name: Up to date versions - Special case - Symfony 5.4
+            php-version: '${{ needs.fetch-supported-versions.outputs.php-max }}'
+            symfony-version: '5.4'
+            # Fix - behat/gherkin => Avoid issue with behat <-> gherkin packages (See https://github.com/Behat/Gherkin/issues/317)
+            # Fix - symfony/yaml - Avoid issue with Sf YAML 6.4+ and Framework bundle
+            pkg-extra-constraints: behat/gherkin:~4.12.0 ${{ ( needs.fetch-supported-versions.outputs.symfony-max == '6.4' ) && 'symfony/yaml:~6.4.0' || '' }}
+          - job-name: Bare minimum # => Lowest versions allowed by composer config
+            php-version: '${{ needs.fetch-supported-versions.outputs.php-min }}'
+            symfony-version: '${{ needs.fetch-supported-versions.outputs.symfony-min }}'
+          - job-name: Bare minimum - Special case - Symfony 5.4
+            php-version: '${{ needs.fetch-supported-versions.outputs.php-min }}'
+            symfony-version: '5.4'
+          - job-name: Late migration - PHP # => Highest symfony version with lowest php version allowed by composer config
+            # Fix - Sf 6.4 require php 8.1 minimum !
+            php-version: ${{ ( needs.fetch-supported-versions.outputs.symfony-max == '6.4' && needs.fetch-supported-versions.outputs.php-min == '8.0' ) && '8.1' || needs.fetch-supported-versions.outputs.php-min }}
+            symfony-version: '${{ needs.fetch-supported-versions.outputs.symfony-max }}'
+          - job-name: Late migration - Symfony # => Lowest symfony version with highest php version allowed by composer config
+            php-version: '${{ needs.fetch-supported-versions.outputs.php-max }}'
+            symfony-version: '${{ needs.fetch-supported-versions.outputs.symfony-min }}'
+            # Fix - behat/gherkin => Avoid issue with behat <-> gherkin packages (See https://github.com/Behat/Gherkin/issues/317)
+            pkg-extra-constraints: behat/gherkin:~4.12.0
     steps:
       - name: Check out code
         uses: actions/checkout@v4
 
+      # Enable coverage only for specific version(s) !
+      # Usually highest version(s), plus additional ones in case of code used only with specific versions
       - name: Enable coverage
-        if: ${{ matrix.php-version == '8.2' }}
+        if: ${{ matrix.php-version == needs.fetch-supported-versions.outputs.php-max }}
         run: |
-          echo "COVERAGE_OUTPUT_STYLE=clover" >> $GITHUB_ENV
           echo "COVERAGE_TYPE=xdebug" >> $GITHUB_ENV
 
       - name: Setup PHP ${{ matrix.php-version }}
+        id: setup-php
         uses: shivammathur/setup-php@v2
         env:
-          update: true # Always use latest available patch for the version
+          update: true # whether to use latest available patch for the version or not
           fail-fast: true # step will fail if an extension or tool fails to set up
         with:
-          php-version: '${{ matrix.php-version }}'
+          php-version: ${{ matrix.php-version }}
           tools: composer
           coverage: ${{ env.COVERAGE_TYPE }}
 
-      - name: Setup cache
-        id: cache
+      - name: Get composer cache directory
+        id: composer-cache
+        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
+
+      - name: Setup cache for PHP ${{ steps.setup-php.outputs.php-version }} & Symfony ${{ matrix.symfony-version }}
         uses: actions/cache@v4
         with:
           path: |
-            ~/.composer
-            ./vendor
-          # Clear the cache if composer json (as composer.lock is in the repo) has been updated
-          key: tests-${{ matrix.php-version }}-${{ matrix.symfony-version }}-${{ matrix.composer-flag }}-${{ hashFiles('composer.json') }}
+            ${{ steps.composer-cache.outputs.dir }}
+          # Clear the cache if composer.json (as composer.lock is not available) has been updated
+          key: tests-php${{ steps.setup-php.outputs.php-version }}-sf${{ matrix.symfony-version }}-${{ hashFiles('composer.json') }}
 
-      - name: Build
+      - name: Build with PHP ${{ steps.setup-php.outputs.php-version }} & Symfony ${{ matrix.symfony-version }}
         run: |
-          SF_VERSION=${{ matrix.symfony-version }}
-          # Issue with ParamterBag below 4.4.30 => https://github.com/symfony/symfony/commit/3eca446b21607ea1c7a865ece2dd8254c33679cc
-          test '${{ matrix.symfony-version }}' = '4.4' && test '${{ matrix.php-version }}' = '8.2' && SF_VERSION=4.4.30
-          composer require -W ${{ env.COMPOSER_OPTIONS }} ${{ matrix.composer-flag }} \
-            symfony/validator:^$SF_VERSION \
-          && composer update ${{ env.COMPOSER_OPTIONS }} ${{ matrix.composer-flag }} \
+          SF_CONSTRAINT="~${{ matrix.symfony-version }}.0"
+          composer require -W \
+            symfony/validator:${SF_CONSTRAINT} \
+            ${{ matrix.pkg-extra-constraints }} \
           && make build
 
       - name: Tests
@@ -84,8 +130,7 @@ jobs:
 
       - name: Create "unit tests" reports group
         if: ${{ env.COVERAGE_TYPE == 'xdebug' }}
-        id: unit-tests-coverage-group
-        uses: yoanm/temp-reports-group-workspace/gha-create@v0
+        uses: yoanm/temp-reports-group-workspace/create-group@v0
         with:
           name: unit-tests
           format: clover
@@ -96,10 +141,9 @@ jobs:
             sf-${{ matrix.symfony-version }}
           path: build/coverage-groups
 
-      - name: Create "functional tests" coverage group
+      - name: Create "functional tests" reports group
         if: ${{ env.COVERAGE_TYPE == 'xdebug' }}
-        id: functional-tests-coverage-group
-        uses: yoanm/temp-reports-group-workspace/gha-create@v0
+        uses: yoanm/temp-reports-group-workspace/create-group@v0
         with:
           name: functional-tests
           format: clover
@@ -116,37 +160,51 @@ jobs:
         if: ${{ env.COVERAGE_TYPE == 'xdebug' }}
         uses: actions/upload-artifact@v4
         with:
-          name: coverage-groups-php${{ matrix.php-version }}-sf${{ matrix.symfony-version }}
+          name: coverage-groups-php${{ steps.setup-php.outputs.php-version }}-sf${{ matrix.symfony-version }}
           path: build/coverage-groups
           if-no-files-found: error
 
   static-checks:
     name: Static analysis
+    needs: [fetch-supported-versions]
     runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    env:
+      PHP_VERSION: ${{ needs.fetch-supported-versions.outputs.php-max }}
+      SYMFONY_VERSION: ${{ needs.fetch-supported-versions.outputs.symfony-max }}
     steps:
       - uses: actions/checkout@v4
 
-      - name: Setup PHP 8.2
+      - name: Setup PHP ${{ env.PHP_VERSION }}
+        id: setup-php
         uses: shivammathur/setup-php@v2
+        env:
+          update: true # Always use latest available patch for the version
+          fail-fast: true # step will fail if an extension or tool fails to set up
         with:
-          php-version: 8.2 # Latest supported
+          php-version: ${{ env.PHP_VERSION }}
           tools: composer
           coverage: none
-        env:
-          # Always use latest available patch for the version
-          update: true
 
-      - name: Setup cache
-        id: cache
+      - name: Get composer cache directory
+        id: composer-cache
+        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
+
+      - name: Setup cache for PHP ${{ steps.setup-php.outputs.php-version }} & Symfony ${{ env.SYMFONY_VERSION }}
         uses: actions/cache@v4
         with:
           path: |
-            ~/.composer
-          # Clear the cache if composer json (as composer.lock is in the repo) has been updated
-          key: tests-${{ env.PHP_VERSION }}-${{ hashFiles('composer.json') }}
+            ${{ steps.composer-cache.outputs.dir }}
+          # Clear the cache if composer.json (as composer.lock is not available) has been updated
+          key: tests-php${{ steps.setup-php.outputs.php-version }}-sf${{ env.SYMFONY_VERSION }}-${{ hashFiles('composer.json') }}
 
-      - name: Build
-        run: make build
+      - name: Build with PHP ${{ steps.setup-php.outputs.php-version }} & Symfony ${{ env.SYMFONY_VERSION }}
+        run: |
+          SF_CONSTRAINT="~${{ env.SYMFONY_VERSION }}.0"
+          composer require -W \
+            symfony/validator:${SF_CONSTRAINT} \
+          && make build
 
       - name: ComposerRequireChecker
         uses: docker://webfactory/composer-require-checker:4.5.0
@@ -156,56 +214,77 @@ jobs:
         uses: actions/dependency-review-action@v4
 
   nightly-tests:
-    name: Nightly - Symfony ${{ matrix.symfony-version }}
+    name: Nightly - ${{ matrix.job-name }}
+    needs: [ fetch-supported-versions, tests ]
+    if: ${{ github.event_name == 'push' || ( github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'with-nightly-tests') ) }}
     runs-on: ubuntu-latest
-    env:
-      COMPOSER_OPTIONS: '--optimize-autoloader --ignore-platform-req=php+'
+    permissions:
+      contents: read
     continue-on-error: true
-    needs: [ static-checks, tests ]
+    env:
+      COMPOSER_IGNORE_PLATFORM_REQ: 'php+'
     strategy:
       fail-fast: false
-      max-parallel: 4
       matrix:
-        php-version:
-          - '8.3' # Current php dev version
-        symfony-version:
-          - '4.4' # Lowest LTS
-          - '5.4' # Latest LTS
-          - '6.0' # Current major version
         include:
-          - symfony-version: '6.3' # Next symfony minor version to manage with latest supported PHP version
-            php-version: '8.2'
+          - job-name: PHP - With highest supported Symfony versions
+            php-version: ${{ needs.fetch-supported-versions.outputs.php-next }}
+            symfony-version: ${{ needs.fetch-supported-versions.outputs.symfony-max }}
+            # Fix - behat/gherkin => Avoid issue with behat <-> gherkin packages (See https://github.com/Behat/Gherkin/issues/317)
+            pkg-extra-constraints: behat/gherkin:~4.12.0
+          - job-name: PHP - With lowest supported Symfony versions
+            php-version: ${{ needs.fetch-supported-versions.outputs.php-next }}
+            symfony-version: ${{ needs.fetch-supported-versions.outputs.symfony-min }}
+            # Fix - behat/gherkin => Avoid issue with behat <-> gherkin packages (See https://github.com/Behat/Gherkin/issues/317)
+            pkg-extra-constraints: behat/gherkin:~4.12.0
+          - job-name: Symfony - With highest supported PHP version
+            php-version: ${{ needs.fetch-supported-versions.outputs.php-max }}
+            symfony-version: ${{ needs.fetch-supported-versions.outputs.symfony-next }}
+            # Fix - behat/gherkin => Avoid issue with behat <-> gherkin packages (See https://github.com/Behat/Gherkin/issues/317)
+            # Fix - symfony/framework-bundle - Framework bundle <7.0 require php 8.1 minimum !
+            pkg-extra-constraints: behat/gherkin:~4.12.0 ${{ ( needs.fetch-supported-versions.outputs.symfony-next == '7.0' && needs.fetch-supported-versions.outputs.php-max == '8.4' ) && 'symfony/framework-bundle:~7.0.0@dev' || '' }}
+          - job-name: Symfony - With lowest supported PHP version
+            # Fix - Sf 7.0 require php 8.1 minimum, most of deps require 8.2 !
+            php-version: ${{ ( needs.fetch-supported-versions.outputs.symfony-next == '6.3' && needs.fetch-supported-versions.outputs.php-min == '8.0' ) && '8.1' || needs.fetch-supported-versions.outputs.php-min }}
+            symfony-version: ${{ needs.fetch-supported-versions.outputs.symfony-next }}
+            # Fix - behat/gherkin => Avoid issue with behat <-> gherkin packages (See https://github.com/Behat/Gherkin/issues/317)
+            # Fix - symfony/framework-bundle - Framework bundle <7.0 require php 8.1 minimum !
+            pkg-extra-constraints: behat/gherkin:~4.12.0 ${{ ( needs.fetch-supported-versions.outputs.symfony-next == '7.0' && needs.fetch-supported-versions.outputs.php-min == '8.0' ) && 'symfony/framework-bundle:~7.0.0@dev' || '' }}
 
     steps:
       - name: Check out code
         uses: actions/checkout@v4
 
       - name: Setup PHP ${{ matrix.php-version }}
+        id: setup-php
         uses: shivammathur/setup-php@v2
+        env:
+          update: true # whether to use latest available patch for the version or not
+          fail-fast: true # step will fail if an extension or tool fails to set up
         with:
-          php-version: '${{ matrix.php-version }}'
+          php-version: ${{ matrix.php-version }}
           tools: composer
           coverage: none
-        env:
-          # Always use latest available patch for the version
-          update: true
 
-      - name: Setup cache
-        id: cache
+      - name: Get composer cache directory
+        id: composer-cache
+        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
+
+      - name: Setup cache for PHP ${{ steps.setup-php.outputs.php-version }} & Symfony ${{ matrix.symfony-version }}
         uses: actions/cache@v4
         with:
           path: |
-            ~/.composer
-            ./vendor
-          # Clear the cache if composer json (as composer.lock is in the repo) has been updated
-          key: tests-${{ matrix.php-version }}-${{ matrix.symfony-version }}-${{ hashFiles('composer.json') }}
+            ${{ steps.composer-cache.outputs.dir }}
+          # Clear the cache if composer.json (as composer.lock is not available) has been updated
+          key: tests-php${{ steps.setup-php.outputs.php-version }}-sf${{ matrix.symfony-version }}-${{ hashFiles('composer.json') }}
 
-      - name: Build
+      - name: Build with PHP ${{ steps.setup-php.outputs.php-version }} & Symfony ${{ matrix.symfony-version }}
         run: |
+          SF_CONSTRAINT="~${{ matrix.symfony-version }}.0@dev"
           composer config minimum-stability dev \
-          && composer require -W ${{ env.COMPOSER_OPTIONS }} \
-            symfony/validator:^${{ matrix.symfony-version }} \
-          && composer update ${{ env.COMPOSER_OPTIONS }} \
+          && composer require -W \
+            symfony/validator:${SF_CONSTRAINT} \
+            ${{ matrix.pkg-extra-constraints }} \
           && make build
 
       - name: Test
